config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles
  root 'welcome#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :area
  mount_uploader :picture, PictureUploader
  validates :titulo, presence: true, length: { minimum: 5 }
  validates :contenido, presence: true, length: { maximum: 140 }

  def self.filtro_areas(parametro)
    if parametro
      where("area_id =?", parametro)
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.page(params[:page]).per(4)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:titulo, :contenido, :picture, :area_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.filtro_areas(params[:area]).page(params[:page]).per(3)
    @areas = Area.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, html: { multipart: true }) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </div>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
  <span>
    <%= f.collection_select :area_id, Area.all, :id, :nombre %>
  </span>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th>Fecha creación</th>
      <th>Fecha modificación</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.titulo %></td>
        <td><%= article.contenido %></td>
        <td><%= article.created_at.to_formatted_s(:db) %></td>
        <td><%= article.updated_at.to_formatted_s(:db) %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @articles %>
<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @article.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @article.contenido %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pacartaya</title>
    <%= stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <% if notice %>
    <div data-alert class="alert-box" tabindex="0" aria-live="assertive" role="alertdialog">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div data-alert class="alert-box alert" tabindex="0" aria-live="assertive" role="alertdialog">
      <%= alert %>
    </div>
  <% end %>
    <div class="contain-to-grid sticky">
      <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
        <ul class="title-area" >
          <li class="name">
            <h1><%= link_to 'Partido Andalucista de Cartaya', root_path %></h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <% if user_signed_in? %>
          <ul class="left">
            <li><%= link_to current_user.email %></li>
          </ul>
          <% end %>
          <ul class="right">
            <li><%= link_to 'Portada', root_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to 'Articulos', articles_path %></li>
            <li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete  %></li>
            <% else %>
            <li><%= link_to 'Iniciar sesión', new_user_session_path %></li>
            <% end %>
          </ul>
        </section>
      </nav>
    </div>
    <%= yield %>

  </body>
  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>Light Coast Labs</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="large-9 columns" role="content">
    <section>
      <% @articles.each do |articulo| %>
        <article>
          <h3><%= articulo.titulo %><%= articulo.area.nombre %></h3>
          <h6>Escrito el <%= articulo.created_at.to_formatted_s(:db) %></h6>
          <div class="row">
            <div class="large-6 columns">
              <p><%= truncate(articulo.contenido, length: 260) %></p>
              <%= link_to 'Artículo completo', article_path(articulo), class: "right" %>
            </div>
            <div class="large-6 columns">
            <% if articulo.picture? %>
              <%= image_tag articulo.picture.url, alt: 'Sin acceso a la imagen'  %>
            <% else %>
              <img src="http://placehold.it/400x240&text=[img]"/>
            <% end %>
            </div>
          </div>
        </article>
      <% end %>
      <%= paginate @articles, area: params[:area] %>
    </section>
  </div>
  <aside class="large-3 columns">
    <h5>Categorias</h5>
    <ul class="side-nav">
    <% @areas.each do |area| %>
      <li><%= link_to area.nombre, root_path(area: area) %></li>
    <% end %>
    </ul>
    <div class="panel">
      <h5>Featured</h5>
      <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>
      <a href="#">Read More →</a>
    </div>
  </aside>
</div>